squash 'resources/unpacked/devtools' changes from dccc514d7..f0f7fb7c4
f0f7fb7c4 [DevTools] Updates Karma to report coverage
ae649fe56 Always add braces to single-line if-statements
c1879a6cf [devtools] Disable debug breaks for live expressions.
8236a326b [DevTools] Adds Trie tests
1a7016a01 [DevTools] Emit Network.*ExtraInfo events for service workers
805e554b1 DevTools: Add placeholders in grdp files to avoid translations
b5fe9d93b [DevTools] Adds CSS Overview Panel
6c22ea502 [DevTools] Fix "TypeError: database.getTableNames is not a function" when adding/removing tables in the Application tab
7de282928 Move InspectorFrontendHostAPI to externs
ad7c3bb1b [devtools] Adds cookie value preview
277695e81 [devtools] Add relative coverage to timeline
df74e3dfb [DevTools] Adds Color parse Karma tests.
c40cf55f7 [devtools] Properly render whitespace in strings in the Watch panel.
6daf29381 [Devtools] Roll Lighthouse to v5.4.0
19a7a7122 [DevTools] Fix copying PowerShell commands
eb24852fc [DevTools] Add targets to protocol monitor
3d7676f6a [DevTools] Fix request cookies view with no cookies
11c9884e6 DevTools: Localize strings in the command menu

git-subtree-dir: resources/unpacked/devtools
git-subtree-split: f0f7fb7c420d79afee01fbe6b854b19fde88d925